# Generated by Django 4.0.3 on 2022-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventId', models.CharField(max_length=30)),
                ('VoterAddress', models.CharField(max_length=70)),
                ('ProposalName', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ContractEvent',
            },
        ),
    ]
